version: "3"

services:
  # Development related
  test-sqlite:
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    entrypoint: pytest
    volumes:
      - ./areasBackend:/opt/code

  test-postgresql:
    env_file: environment.env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    entrypoint: pytest
    depends_on:
      - db
    volumes:
      - ./areasBackend:/opt/code

  # Pipeline actions
  test:
    env_file: environment.env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    entrypoint: pytest
    depends_on:
      - db

  static-analysis:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    entrypoint: flake8

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
      args:
        # These values should be in sync with environment
        # for development. If you change them, you'll
        # need to rebuild the container
        - POSTGRES_DB=areas
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=somepassword
        - POSTGRES_PORT=5432

  # Producion related
  # Note that db-debug is the same as db, but it exposes locally
  # port 5432 to access PostgreSQL
  db-debug:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
      args:
        # These values should be in sync with environment
        # for development. If you change them, you'll
        # need to rebuild the container
        - POSTGRES_DB=areas
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=somepassword
        - POSTGRES_PORT=5432
    ports:
      - "5437:5432"

  server:
    env_file: environment.env
    image: areas_server
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "7007:8000"
    depends_on:
      - db
